# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reflex_control/FollowWaypointsFeedback.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class FollowWaypointsFeedback(genpy.Message):
  _md5sum = "0e2fc254189e46d3d827d900a29d7809"
  _type = "reflex_control/FollowWaypointsFeedback"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#feedback definition
geometry_msgs/Pose desired
geometry_msgs/Pose actual
geometry_msgs/Pose error
float64 progress


================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  __slots__ = ['desired','actual','error','progress']
  _slot_types = ['geometry_msgs/Pose','geometry_msgs/Pose','geometry_msgs/Pose','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       desired,actual,error,progress

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(FollowWaypointsFeedback, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose()
      if self.error is None:
        self.error = geometry_msgs.msg.Pose()
      if self.progress is None:
        self.progress = 0.
    else:
      self.desired = geometry_msgs.msg.Pose()
      self.actual = geometry_msgs.msg.Pose()
      self.error = geometry_msgs.msg.Pose()
      self.progress = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_22d().pack(_x.desired.position.x, _x.desired.position.y, _x.desired.position.z, _x.desired.orientation.x, _x.desired.orientation.y, _x.desired.orientation.z, _x.desired.orientation.w, _x.actual.position.x, _x.actual.position.y, _x.actual.position.z, _x.actual.orientation.x, _x.actual.orientation.y, _x.actual.orientation.z, _x.actual.orientation.w, _x.error.position.x, _x.error.position.y, _x.error.position.z, _x.error.orientation.x, _x.error.orientation.y, _x.error.orientation.z, _x.error.orientation.w, _x.progress))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose()
      if self.error is None:
        self.error = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 176
      (_x.desired.position.x, _x.desired.position.y, _x.desired.position.z, _x.desired.orientation.x, _x.desired.orientation.y, _x.desired.orientation.z, _x.desired.orientation.w, _x.actual.position.x, _x.actual.position.y, _x.actual.position.z, _x.actual.orientation.x, _x.actual.orientation.y, _x.actual.orientation.z, _x.actual.orientation.w, _x.error.position.x, _x.error.position.y, _x.error.position.z, _x.error.orientation.x, _x.error.orientation.y, _x.error.orientation.z, _x.error.orientation.w, _x.progress,) = _get_struct_22d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_22d().pack(_x.desired.position.x, _x.desired.position.y, _x.desired.position.z, _x.desired.orientation.x, _x.desired.orientation.y, _x.desired.orientation.z, _x.desired.orientation.w, _x.actual.position.x, _x.actual.position.y, _x.actual.position.z, _x.actual.orientation.x, _x.actual.orientation.y, _x.actual.orientation.z, _x.actual.orientation.w, _x.error.position.x, _x.error.position.y, _x.error.position.z, _x.error.orientation.x, _x.error.orientation.y, _x.error.orientation.z, _x.error.orientation.w, _x.progress))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.desired is None:
        self.desired = geometry_msgs.msg.Pose()
      if self.actual is None:
        self.actual = geometry_msgs.msg.Pose()
      if self.error is None:
        self.error = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 176
      (_x.desired.position.x, _x.desired.position.y, _x.desired.position.z, _x.desired.orientation.x, _x.desired.orientation.y, _x.desired.orientation.z, _x.desired.orientation.w, _x.actual.position.x, _x.actual.position.y, _x.actual.position.z, _x.actual.orientation.x, _x.actual.orientation.y, _x.actual.orientation.z, _x.actual.orientation.w, _x.error.position.x, _x.error.position.y, _x.error.position.z, _x.error.orientation.x, _x.error.orientation.y, _x.error.orientation.z, _x.error.orientation.w, _x.progress,) = _get_struct_22d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_22d = None
def _get_struct_22d():
    global _struct_22d
    if _struct_22d is None:
        _struct_22d = struct.Struct("<22d")
    return _struct_22d
