# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from reflex_control/follow_waypointsResult.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class follow_waypointsResult(genpy.Message):
  _md5sum = "20285b7d4b361411f5aecea3b0272841"
  _type = "reflex_control/follow_waypointsResult"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
#results definition

geometry_msgs/Pose final_pose
int32 error_code
int32 SUCCESSFUL = 0
int32 PREEMPTED = -1
int32 INVALID_GOAL = -2

string error_string


================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of position and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w
"""
  # Pseudo-constants
  SUCCESSFUL = 0
  PREEMPTED = -1
  INVALID_GOAL = -2

  __slots__ = ['final_pose','error_code','error_string']
  _slot_types = ['geometry_msgs/Pose','int32','string']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       final_pose,error_code,error_string

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(follow_waypointsResult, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      if self.error_code is None:
        self.error_code = 0
      if self.error_string is None:
        self.error_string = ''
    else:
      self.final_pose = geometry_msgs.msg.Pose()
      self.error_code = 0
      self.error_string = ''

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_7di().pack(_x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.error_code))
      _x = self.error_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.error_code,) = _get_struct_7di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_string = str[start:end].decode('utf-8')
      else:
        self.error_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_7di().pack(_x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.error_code))
      _x = self.error_string
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.final_pose is None:
        self.final_pose = geometry_msgs.msg.Pose()
      end = 0
      _x = self
      start = end
      end += 60
      (_x.final_pose.position.x, _x.final_pose.position.y, _x.final_pose.position.z, _x.final_pose.orientation.x, _x.final_pose.orientation.y, _x.final_pose.orientation.z, _x.final_pose.orientation.w, _x.error_code,) = _get_struct_7di().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.error_string = str[start:end].decode('utf-8')
      else:
        self.error_string = str[start:end]
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_7di = None
def _get_struct_7di():
    global _struct_7di
    if _struct_7di is None:
        _struct_7di = struct.Struct("<7di")
    return _struct_7di
