(cl:defpackage reflex_control-srv
  (:use )
  (:export
   "CHANGE_PARAM"
   "<CHANGE_PARAM-REQUEST>"
   "CHANGE_PARAM-REQUEST"
   "<CHANGE_PARAM-RESPONSE>"
   "CHANGE_PARAM-RESPONSE"
   "SWITCH_CONTROL_MODE"
   "<SWITCH_CONTROL_MODE-REQUEST>"
   "SWITCH_CONTROL_MODE-REQUEST"
   "<SWITCH_CONTROL_MODE-RESPONSE>"
   "SWITCH_CONTROL_MODE-RESPONSE"
  ))

