// Generated by gencpp from file reflex_control/change_paramResponse.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_CHANGE_PARAMRESPONSE_H
#define REFLEX_CONTROL_MESSAGE_CHANGE_PARAMRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_control
{
template <class ContainerAllocator>
struct change_paramResponse_
{
  typedef change_paramResponse_<ContainerAllocator> Type;

  change_paramResponse_()
    : fb(false)  {
    }
  change_paramResponse_(const ContainerAllocator& _alloc)
    : fb(false)  {
  (void)_alloc;
    }



   typedef uint8_t _fb_type;
  _fb_type fb;





  typedef boost::shared_ptr< ::reflex_control::change_paramResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_control::change_paramResponse_<ContainerAllocator> const> ConstPtr;

}; // struct change_paramResponse_

typedef ::reflex_control::change_paramResponse_<std::allocator<void> > change_paramResponse;

typedef boost::shared_ptr< ::reflex_control::change_paramResponse > change_paramResponsePtr;
typedef boost::shared_ptr< ::reflex_control::change_paramResponse const> change_paramResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_control::change_paramResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_control::change_paramResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reflex_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reflex_control': ['/home/patrick/reflex_control/src/reflex_control/msg', '/home/patrick/reflex_control/devel/share/reflex_control/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::change_paramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::change_paramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::change_paramResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::change_paramResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::change_paramResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::change_paramResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_control::change_paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "64d12b326124d8fe576ffce2ad5eb111";
  }

  static const char* value(const ::reflex_control::change_paramResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x64d12b326124d8feULL;
  static const uint64_t static_value2 = 0x576ffce2ad5eb111ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_control::change_paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_control/change_paramResponse";
  }

  static const char* value(const ::reflex_control::change_paramResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_control::change_paramResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool fb\n\
\n\
";
  }

  static const char* value(const ::reflex_control::change_paramResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_control::change_paramResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fb);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct change_paramResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_control::change_paramResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_control::change_paramResponse_<ContainerAllocator>& v)
  {
    s << indent << "fb: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.fb);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_CHANGE_PARAMRESPONSE_H
