// Generated by gencpp from file reflex_control/change_param.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_CHANGE_PARAM_H
#define REFLEX_CONTROL_MESSAGE_CHANGE_PARAM_H

#include <ros/service_traits.h>


#include <reflex_control/change_paramRequest.h>
#include <reflex_control/change_paramResponse.h>


namespace reflex_control
{

struct change_param
{

typedef change_paramRequest Request;
typedef change_paramResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct change_param
} // namespace reflex_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::reflex_control::change_param > {
  static const char* value()
  {
    return "6f0624492d8870cb5ae06854b717afa1";
  }

  static const char* value(const ::reflex_control::change_param&) { return value(); }
};

template<>
struct DataType< ::reflex_control::change_param > {
  static const char* value()
  {
    return "reflex_control/change_param";
  }

  static const char* value(const ::reflex_control::change_param&) { return value(); }
};


// service_traits::MD5Sum< ::reflex_control::change_paramRequest> should match 
// service_traits::MD5Sum< ::reflex_control::change_param > 
template<>
struct MD5Sum< ::reflex_control::change_paramRequest>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_control::change_param >::value();
  }
  static const char* value(const ::reflex_control::change_paramRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_control::change_paramRequest> should match 
// service_traits::DataType< ::reflex_control::change_param > 
template<>
struct DataType< ::reflex_control::change_paramRequest>
{
  static const char* value()
  {
    return DataType< ::reflex_control::change_param >::value();
  }
  static const char* value(const ::reflex_control::change_paramRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::reflex_control::change_paramResponse> should match 
// service_traits::MD5Sum< ::reflex_control::change_param > 
template<>
struct MD5Sum< ::reflex_control::change_paramResponse>
{
  static const char* value()
  {
    return MD5Sum< ::reflex_control::change_param >::value();
  }
  static const char* value(const ::reflex_control::change_paramResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::reflex_control::change_paramResponse> should match 
// service_traits::DataType< ::reflex_control::change_param > 
template<>
struct DataType< ::reflex_control::change_paramResponse>
{
  static const char* value()
  {
    return DataType< ::reflex_control::change_param >::value();
  }
  static const char* value(const ::reflex_control::change_paramResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_CHANGE_PARAM_H
