// Generated by gencpp from file reflex_control/ControllerSwitch.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_CONTROLLERSWITCH_H
#define REFLEX_CONTROL_MESSAGE_CONTROLLERSWITCH_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_control
{
template <class ContainerAllocator>
struct ControllerSwitch_
{
  typedef ControllerSwitch_<ContainerAllocator> Type;

  ControllerSwitch_()
    : controllerSwitch(0)  {
    }
  ControllerSwitch_(const ContainerAllocator& _alloc)
    : controllerSwitch(0)  {
  (void)_alloc;
    }



   typedef int32_t _controllerSwitch_type;
  _controllerSwitch_type controllerSwitch;





  typedef boost::shared_ptr< ::reflex_control::ControllerSwitch_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_control::ControllerSwitch_<ContainerAllocator> const> ConstPtr;

}; // struct ControllerSwitch_

typedef ::reflex_control::ControllerSwitch_<std::allocator<void> > ControllerSwitch;

typedef boost::shared_ptr< ::reflex_control::ControllerSwitch > ControllerSwitchPtr;
typedef boost::shared_ptr< ::reflex_control::ControllerSwitch const> ControllerSwitchConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_control::ControllerSwitch_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_control::ControllerSwitch_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reflex_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'reflex_control': ['/home/patrick/reflex_control/src/reflex_control/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::ControllerSwitch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::ControllerSwitch_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::ControllerSwitch_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cdf8e0decb24a6822040fa60c5dc790";
  }

  static const char* value(const ::reflex_control::ControllerSwitch_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cdf8e0decb24a68ULL;
  static const uint64_t static_value2 = 0x22040fa60c5dc790ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_control/ControllerSwitch";
  }

  static const char* value(const ::reflex_control::ControllerSwitch_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 controllerSwitch\n\
";
  }

  static const char* value(const ::reflex_control::ControllerSwitch_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.controllerSwitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControllerSwitch_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_control::ControllerSwitch_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_control::ControllerSwitch_<ContainerAllocator>& v)
  {
    s << indent << "controllerSwitch: ";
    Printer<int32_t>::stream(s, indent + "  ", v.controllerSwitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_CONTROLLERSWITCH_H
