// Generated by gencpp from file reflex_control/FollowWaypointsGoal.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H
#define REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace reflex_control
{
template <class ContainerAllocator>
struct FollowWaypointsGoal_
{
  typedef FollowWaypointsGoal_<ContainerAllocator> Type;

  FollowWaypointsGoal_()
    : waypoints()
    , velocities()
    , segment_durations()  {
    }
  FollowWaypointsGoal_(const ContainerAllocator& _alloc)
    : waypoints(_alloc)
    , velocities(_alloc)
    , segment_durations(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose_<ContainerAllocator> >::other >  _waypoints_type;
  _waypoints_type waypoints;

   typedef std::vector<double, typename ContainerAllocator::template rebind<double>::other >  _velocities_type;
  _velocities_type velocities;

   typedef std::vector<ros::Duration, typename ContainerAllocator::template rebind<ros::Duration>::other >  _segment_durations_type;
  _segment_durations_type segment_durations;





  typedef boost::shared_ptr< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsGoal_

typedef ::reflex_control::FollowWaypointsGoal_<std::allocator<void> > FollowWaypointsGoal;

typedef boost::shared_ptr< ::reflex_control::FollowWaypointsGoal > FollowWaypointsGoalPtr;
typedef boost::shared_ptr< ::reflex_control::FollowWaypointsGoal const> FollowWaypointsGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reflex_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reflex_control': ['/home/patrick/reflex_control/src/reflex_control/msg', '/home/patrick/reflex_control/devel/share/reflex_control/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9dd1ecaca467369f5088c9834a86ece";
  }

  static const char* value(const ::reflex_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9dd1ecaca467369ULL;
  static const uint64_t static_value2 = 0xf5088c9834a86eceULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_control/FollowWaypointsGoal";
  }

  static const char* value(const ::reflex_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
#either one velocity/time_stamps or same as waypoints\n\
\n\
geometry_msgs/Pose[] waypoints\n\
float64[] velocities\n\
duration[] segment_durations\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::reflex_control::FollowWaypointsGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.waypoints);
      stream.next(m.velocities);
      stream.next(m.segment_durations);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_control::FollowWaypointsGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_control::FollowWaypointsGoal_<ContainerAllocator>& v)
  {
    s << indent << "waypoints[]" << std::endl;
    for (size_t i = 0; i < v.waypoints.size(); ++i)
    {
      s << indent << "  waypoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "    ", v.waypoints[i]);
    }
    s << indent << "velocities[]" << std::endl;
    for (size_t i = 0; i < v.velocities.size(); ++i)
    {
      s << indent << "  velocities[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.velocities[i]);
    }
    s << indent << "segment_durations[]" << std::endl;
    for (size_t i = 0; i < v.segment_durations.size(); ++i)
    {
      s << indent << "  segment_durations[" << i << "]: ";
      Printer<ros::Duration>::stream(s, indent + "  ", v.segment_durations[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSGOAL_H
