// Generated by gencpp from file reflex_control/FollowWaypointsResult.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H
#define REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace reflex_control
{
template <class ContainerAllocator>
struct FollowWaypointsResult_
{
  typedef FollowWaypointsResult_<ContainerAllocator> Type;

  FollowWaypointsResult_()
    : error_code(0)
    , error_string()  {
    }
  FollowWaypointsResult_(const ContainerAllocator& _alloc)
    : error_code(0)
    , error_string(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_string_type;
  _error_string_type error_string;



  enum {
    SUCCESSFUL = 0,
    PREEMPTED = -1,
    INVALID_GOAL = -2,
  };


  typedef boost::shared_ptr< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> const> ConstPtr;

}; // struct FollowWaypointsResult_

typedef ::reflex_control::FollowWaypointsResult_<std::allocator<void> > FollowWaypointsResult;

typedef boost::shared_ptr< ::reflex_control::FollowWaypointsResult > FollowWaypointsResultPtr;
typedef boost::shared_ptr< ::reflex_control::FollowWaypointsResult const> FollowWaypointsResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_control::FollowWaypointsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reflex_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reflex_control': ['/home/fischer/reflex_control/src/reflex_control/msg', '/home/fischer/reflex_control/devel/share/reflex_control/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6a8cd2e22d0e467baf093f6d8eaf6692";
  }

  static const char* value(const ::reflex_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6a8cd2e22d0e467bULL;
  static const uint64_t static_value2 = 0xaf093f6d8eaf6692ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_control/FollowWaypointsResult";
  }

  static const char* value(const ::reflex_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#results definition\n\
\n\
#geometry_msgs/Pose final_pose\n\
\n\
int32 error_code\n\
int32 SUCCESSFUL = 0\n\
int32 PREEMPTED = -1\n\
int32 INVALID_GOAL = -2\n\
\n\
string error_string\n\
\n\
";
  }

  static const char* value(const ::reflex_control::FollowWaypointsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.error_code);
      stream.next(m.error_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowWaypointsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_control::FollowWaypointsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_control::FollowWaypointsResult_<ContainerAllocator>& v)
  {
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_FOLLOWWAYPOINTSRESULT_H
