// Generated by gencpp from file reflex_control/follow_waypointsResult.msg
// DO NOT EDIT!


#ifndef REFLEX_CONTROL_MESSAGE_FOLLOW_WAYPOINTSRESULT_H
#define REFLEX_CONTROL_MESSAGE_FOLLOW_WAYPOINTSRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace reflex_control
{
template <class ContainerAllocator>
struct follow_waypointsResult_
{
  typedef follow_waypointsResult_<ContainerAllocator> Type;

  follow_waypointsResult_()
    : final_pose()
    , error_code(0)
    , error_string()  {
    }
  follow_waypointsResult_(const ContainerAllocator& _alloc)
    : final_pose(_alloc)
    , error_code(0)
    , error_string(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _final_pose_type;
  _final_pose_type final_pose;

   typedef int32_t _error_code_type;
  _error_code_type error_code;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _error_string_type;
  _error_string_type error_string;



  enum {
    SUCCESSFUL = 0,
    PREEMPTED = -1,
    INVALID_GOAL = -2,
  };


  typedef boost::shared_ptr< ::reflex_control::follow_waypointsResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::reflex_control::follow_waypointsResult_<ContainerAllocator> const> ConstPtr;

}; // struct follow_waypointsResult_

typedef ::reflex_control::follow_waypointsResult_<std::allocator<void> > follow_waypointsResult;

typedef boost::shared_ptr< ::reflex_control::follow_waypointsResult > follow_waypointsResultPtr;
typedef boost::shared_ptr< ::reflex_control::follow_waypointsResult const> follow_waypointsResultConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::reflex_control::follow_waypointsResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace reflex_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'reflex_control': ['/home/patrick/reflex_control/src/reflex_control/msg', '/home/patrick/reflex_control/devel/share/reflex_control/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'actionlib': ['/opt/ros/kinetic/share/actionlib/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::reflex_control::follow_waypointsResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::reflex_control::follow_waypointsResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::reflex_control::follow_waypointsResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "20285b7d4b361411f5aecea3b0272841";
  }

  static const char* value(const ::reflex_control::follow_waypointsResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x20285b7d4b361411ULL;
  static const uint64_t static_value2 = 0xf5aecea3b0272841ULL;
};

template<class ContainerAllocator>
struct DataType< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "reflex_control/follow_waypointsResult";
  }

  static const char* value(const ::reflex_control::follow_waypointsResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#results definition\n\
\n\
geometry_msgs/Pose final_pose\n\
int32 error_code\n\
int32 SUCCESSFUL = 0\n\
int32 PREEMPTED = -1\n\
int32 INVALID_GOAL = -2\n\
\n\
string error_string\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::reflex_control::follow_waypointsResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.final_pose);
      stream.next(m.error_code);
      stream.next(m.error_string);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct follow_waypointsResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::reflex_control::follow_waypointsResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::reflex_control::follow_waypointsResult_<ContainerAllocator>& v)
  {
    s << indent << "final_pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.final_pose);
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
    s << indent << "error_string: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.error_string);
  }
};

} // namespace message_operations
} // namespace ros

#endif // REFLEX_CONTROL_MESSAGE_FOLLOW_WAYPOINTSRESULT_H
