(cl:defpackage reflex_control-msg
  (:use )
  (:export
   "<CONTROLLERSWITCH>"
   "CONTROLLERSWITCH"
   "<JOINTTORQUECOMPARISON>"
   "JOINTTORQUECOMPARISON"
   "<FOLLOW_WAYPOINTSACTION>"
   "FOLLOW_WAYPOINTSACTION"
   "<FOLLOW_WAYPOINTSACTIONFEEDBACK>"
   "FOLLOW_WAYPOINTSACTIONFEEDBACK"
   "<FOLLOW_WAYPOINTSACTIONGOAL>"
   "FOLLOW_WAYPOINTSACTIONGOAL"
   "<FOLLOW_WAYPOINTSACTIONRESULT>"
   "FOLLOW_WAYPOINTSACTIONRESULT"
   "<FOLLOW_WAYPOINTSFEEDBACK>"
   "FOLLOW_WAYPOINTSFEEDBACK"
   "<FOLLOW_WAYPOINTSGOAL>"
   "FOLLOW_WAYPOINTSGOAL"
   "<FOLLOW_WAYPOINTSRESULT>"
   "FOLLOW_WAYPOINTSRESULT"
  ))

