(cl:defpackage reflex_control-msg
  (:use )
  (:export
   "<CONTROLLERSWITCH>"
   "CONTROLLERSWITCH"
   "<FOLLOWWAYPOINTSACTION>"
   "FOLLOWWAYPOINTSACTION"
   "<FOLLOWWAYPOINTSACTIONFEEDBACK>"
   "FOLLOWWAYPOINTSACTIONFEEDBACK"
   "<FOLLOWWAYPOINTSACTIONGOAL>"
   "FOLLOWWAYPOINTSACTIONGOAL"
   "<FOLLOWWAYPOINTSACTIONRESULT>"
   "FOLLOWWAYPOINTSACTIONRESULT"
   "<FOLLOWWAYPOINTSFEEDBACK>"
   "FOLLOWWAYPOINTSFEEDBACK"
   "<FOLLOWWAYPOINTSGOAL>"
   "FOLLOWWAYPOINTSGOAL"
   "<FOLLOWWAYPOINTSRESULT>"
   "FOLLOWWAYPOINTSRESULT"
   "<JOINTTORQUECOMPARISON>"
   "JOINTTORQUECOMPARISON"
   "<CARTESIAN_WAYPOINT>"
   "CARTESIAN_WAYPOINT"
  ))

