; Auto-generated. Do not edit!


(cl:in-package reflex_control-msg)


;//! \htmlinclude FollowWaypointsGoal.msg.html

(cl:defclass <FollowWaypointsGoal> (roslisp-msg-protocol:ros-message)
  ((waypoints
    :reader waypoints
    :initarg :waypoints
    :type (cl:vector reflex_control-msg:cartesian_waypoint)
   :initform (cl:make-array 0 :element-type 'reflex_control-msg:cartesian_waypoint :initial-element (cl:make-instance 'reflex_control-msg:cartesian_waypoint))))
)

(cl:defclass FollowWaypointsGoal (<FollowWaypointsGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowWaypointsGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowWaypointsGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name reflex_control-msg:<FollowWaypointsGoal> is deprecated: use reflex_control-msg:FollowWaypointsGoal instead.")))

(cl:ensure-generic-function 'waypoints-val :lambda-list '(m))
(cl:defmethod waypoints-val ((m <FollowWaypointsGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader reflex_control-msg:waypoints-val is deprecated.  Use reflex_control-msg:waypoints instead.")
  (waypoints m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowWaypointsGoal>) ostream)
  "Serializes a message object of type '<FollowWaypointsGoal>"
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'waypoints))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (roslisp-msg-protocol:serialize ele ostream))
   (cl:slot-value msg 'waypoints))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowWaypointsGoal>) istream)
  "Deserializes a message object of type '<FollowWaypointsGoal>"
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'waypoints) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'waypoints)))
    (cl:dotimes (i __ros_arr_len)
    (cl:setf (cl:aref vals i) (cl:make-instance 'reflex_control-msg:cartesian_waypoint))
  (roslisp-msg-protocol:deserialize (cl:aref vals i) istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowWaypointsGoal>)))
  "Returns string type for a message object of type '<FollowWaypointsGoal>"
  "reflex_control/FollowWaypointsGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowWaypointsGoal)))
  "Returns string type for a message object of type 'FollowWaypointsGoal"
  "reflex_control/FollowWaypointsGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowWaypointsGoal>)))
  "Returns md5sum for a message object of type '<FollowWaypointsGoal>"
  "07520baf25a4c29745adfadd9061229a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowWaypointsGoal)))
  "Returns md5sum for a message object of type 'FollowWaypointsGoal"
  "07520baf25a4c29745adfadd9061229a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowWaypointsGoal>)))
  "Returns full string definition for message of type '<FollowWaypointsGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#either one velocity/time_stamps or same as waypoints~%~%cartesian_waypoint[] waypoints~%~%~%================================================================================~%MSG: reflex_control/cartesian_waypoint~%geometry_msgs/Pose wp~%float64 vel~%duration dur~%float64 tol_trans~%float64 tol_angle~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowWaypointsGoal)))
  "Returns full string definition for message of type 'FollowWaypointsGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#goal definition~%#either one velocity/time_stamps or same as waypoints~%~%cartesian_waypoint[] waypoints~%~%~%================================================================================~%MSG: reflex_control/cartesian_waypoint~%geometry_msgs/Pose wp~%float64 vel~%duration dur~%float64 tol_trans~%float64 tol_angle~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of position and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowWaypointsGoal>))
  (cl:+ 0
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'waypoints) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ (roslisp-msg-protocol:serialization-length ele))))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowWaypointsGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowWaypointsGoal
    (cl:cons ':waypoints (waypoints msg))
))
